### ISSUE TITLE
BibLaTeX and biber

### ISSUE THREAD

**Issue by adoa** [ransford/pdflatex-makefile#17]
I would like to migrate from bibtex to [biblatex](http://ctan.org/pkg/biblatex) and the new backend biber. 
Would be awesome if pdflatex-makefile could check for `\usepackage[options]{biblatex}` and then search for the `\addbibresource{}` defined by biblatex instead of (or in addition to?) `\bibliography{}`.

One complication: biblatex defines biber as the default backend, this should motivate pdflatex-makefile to call biber instead of bibtex. However, one can just as well give the option `[backend=bibtex]` which prepares the invocation of bibtex – and the two are not compatible.

[edit:] biblatex and biber use additional auxiliary files – those should be cleaned as well.

Once again, my make/shell/grep/sed magic skills do not suffice to do so myself.

**Comment by ransford** [comment]
Call me old fashioned, but I've never used biblatex or biber.  However, I'm willing to implement this support (by grepping shamelessly).  Probably next week.

**Comment by ransford** [comment]
What are biber's auxiliary files called?

**Comment by adoa** [comment]
If I get this correctly, then the biblatex package always creates one additional auxiliary file: `<target>.run.xml`.  It is being created while compiling with `pdflatex`.

With `\usepackage[backend=bibtex]{biblatex}` there is an additional auxiliary file for `bibtex` called `<target>-blx.bib`.

Instead using the default `backend=biber` makes `pdflatex` create an additional auxiliary file for `biber` called `<target>.bcf`.

Both `biber` and `bibtex` create the `<target>.bbl` later used by `pdflatex` and write their respective log into the same file `<target>.blg`.

**Comment by rjku** [comment]
Is there any progress on this point?

**Comment by ransford** [comment]
No, other things intervened, but I'll take a quick look later today.  Thanks for the ping.  Patches welcome if you want to beat me to it. :-)

**Comment by ransford** [comment]
Try the new `biber` branch of this repo... I'm not certain I have BibLaTeX + biber set up properly on my machine since I don't use them regularly.

**Comment by rjku** [comment]
(I am not 100% sure I did everything right but) I have tried it and it does not work. 
Namely, it does not compile the bibliography.
I need to run externally `< biber [BibliographyFileName (without .bib)] >` to obtain the bibliography.
Thank you

**Comment by zyrikby** [comment]
Hi Ben,

First of all, I would like to thank you for your makefile. However, as @rjku correctly mentioned, the support of biblatex does not work. I did not manage to understand what is wrong, so I would like to ask your help for this.

**Comment by ransford** [comment]
patches/PRs welcome
