### ISSUE TITLE
Aux file of target is deleted

### ISSUE THREAD

**Issue by pierroweb** [ransford/pdflatex-makefile#24]
Hi,

I'm not sure this comes from pdflatex, but when I run pdflatex alone this behavior below does not appear.

The aux file of the target is deleted after "make". Everything is compiled properly though.

However, aux files of included files are not deleted (say, if I have ```\input{secondfile}``` in my target latex file, then secondfile.aux will not be deleted, while the aux file of the Makefile target is deleted.)

I need to keep aux files for autocomplete of labels in my editor.

Is it possible that pdflatex-makefile is responsible for the deletion of the aux file of the target?

Thanks in advance!

**Comment by ransford** [comment]
Yes, it's absolutely the Makefile's fault, specifically the line that says

    .INTERMEDIATE: $(AUXFILES)

It shouldn't break anything to leave the main .aux file after typesetting, so I am going to solve this problem by removing that line.

**Comment by pierroweb** [comment]
Wow! that was reactive. This project helps me be productive with my research :)
Thank you Ben

**Comment by ransford** [comment]
Note that I put the `.INTERMEDIATE` targets back in for #36; see the explanation there.  You can still keep those .aux files around if you specify `KEEPAUX=1` (like `make KEEPAUX=1 blahblah.pdf`).
