### ISSUE TITLE
Make rerun detection approach configurable

### ISSUE THREAD

**Issue by elfring** [ransford/pdflatex-makefile#30]
[A constant command is used](https://github.com/ransford/pdflatex-makefile/blob/d2635cbb1e4d2bb9b082ebc2930e5dee9384314a/Makefile.include#L156) so far for the detection if the tool "pdflatex" should be executed again.
How do you think about to support any other search pattern besides an English wording by default?

I suggest to use more variables for the command selection and corresponding parameters in a similar way like it is usual at other places in this make script already.

**Comment by ransford** [comment]
I worry about adding a lot of complexity, but you're right: `"Rerun to"` is English.

**Comment by ransford** [comment]
Does bfd8cde seem right?

**Comment by elfring** [comment]
>I worry about adding a lot of complexity, …

It depends on the interpretation if the addition of a few make variables will result in unwanted consequences.
Are you eventually concerned about a different run time behaviour?


>… "Rerun to" …

How often do you work with corresponding tools which can show an other log message at such a place?
