### ISSUE TITLE
Limit for build runs?

### ISSUE THREAD

**Issue by elfring** [ransford/pdflatex-makefile#31]
[A while loop is used](https://github.com/ransford/pdflatex-makefile/blob/d2635cbb1e4d2bb9b082ebc2930e5dee9384314a/Makefile.include#L156) in a make recipe. It depends on the exit status of a single command so far.
How do you think about to use more conditions so that this approach can be limited on demand?

**Comment by ransford** [comment]
Are you worried about an infinite loop or something else?  So far I haven't heard any reports of the `while` loop failing to terminate...

**Comment by elfring** [comment]
Would you find any higher number of rebuild tries "special" or "unusual"?

**Comment by ransford** [comment]
I don't know the number.  Maybe `N` where `N` is the number of different tools that touch the `.aux` file as part of typesetting?

**Comment by ransford** [comment]
closing; inertia
