### ISSUE TITLE
XeLaTeX support

### ISSUE THREAD

**Issue by ido** [ransford/pdflatex-makefile#33]
To add XeLaTeX support, make -draftmode optional.
Optionally, for cosmetic reasons, you may want to separate out the PDFLATEX variable into PDFLATEX (path to the pdflatex/xelatex binary) and PDFLATEX_OPTS (default options such as -halt-on-error etc.).

Thank you for writing this Makefile.  Detecting "Rerun to" was a very nice touch instead of blindly rerunning. :+1:

**Comment by ransford** [comment]
Hmm, I'm not sure what you mean by XeLaTeX support.  This is what happens on my system (XeTeX 3.14159265-2.6-0.99991):
```shellsession
$ cd example
$ make PDFLATEX=xelatex >& /dev/null
$ ls example.pdf
example.pdf
```

Do you see build errors or some other problem?

**Comment by ido** [comment]
The -draftmode iteration of xelatex in that example is failing, but not being caught because when you set PDFLATEX in your example you remove the halt on error, etc. parameters.  Try just changing pdflatex to xelatex in Makefile.include and see how it errors out because draftmode is not recognized?

**Comment by ransford** [comment]
Closing for lack of movement; patches welcome.
