### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cyphar** [ransford/pdflatex-makefile#34]
Can you please add a license to this project? I'm currently unsure whether or not it is free software.

**Comment by ransford** [comment]
I'm currently unsure whether or not it is "software," but I managed to convince myself that it is for long enough to choose a free-software license and apply it via the README.  Thanks for asking!

**Comment by cyphar** [comment]
Haha. IMO scripts that are longer than 50 lines count as software. So `Makefile.include` definitely counts in my book. Thanks for the quick response! :+1:
