### ISSUE TITLE
Actually maybe do remove those *.aux files?

### ISSUE THREAD

**Issue by sampsyo** [ransford/pdflatex-makefile#36]
Hi, Ben! I feel pretty silly filing this, but the change in 671d7acd46ab0c693bcd8f324c2ee2e2c5efec04 had an unintended consequence, at least for me: it now means that there's no "steady state" where `make` does nothing. Typing `make` now *always* rebuilds the paper.

Here's what's going on: the `%.bbl` rule depends on `%.aux`, which can be produced either by the `-draftmode` command or the main `$(PDFTARGETS)` rule. Before that change, the PDF rule would produce the *.aux file and then immediately delete it, so the BibTeX rule wouldn't need to run again. Now, the BibTeX rule uses the *.aux file to produce the *.bbl, then the PDF rule uses the *.bbl to produce an *.aux that's now newer than the *.bbl, and there you have it.

Would it be too ridiculous to make that `.INTERMEDIATE` declaration somehow optional to satisfy #24?

 💘 ❤️ 💖

**Comment by ransford** [comment]
The right answer is probably to write a caching webserver in PostScript to act as a up-to-dateness oracle.

I'll take a stab at this!

**Comment by ransford** [comment]
.aux files, back and forth, forever

`))<>((`

**Comment by sampsyo** [comment]
`))<>((`

Thank you, dude!
