### ISSUE TITLE
Mixed Implicit and Normal Rule error

### ISSUE THREAD

**Issue by ktiwari9** [ransford/pdflatex-makefile#39]
Hi there,

First of all, thank you for the amazing makefile. I am trying to learn to use it and adapt it for my project. I get the following error:
`Makefile.include:126: *** mixed implicit and normal rules: deprecated syntax` which is generated because of the following line:
```
$(FIGS)/%.pdf: $(FIGS)/%.svg  ## Figures for the manuscript
```

Not sure how to fix it.

**Comment by ktiwari9** [comment]
It says:
```
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by ransford** [comment]
I think it's complaining about the `## ...` comment. If you remove that comment from that line, does the warning go away?

**Comment by ktiwari9** [comment]
Nope. I tried. It still complains about this line : `$(FIGS)/%.pdf: $(FIGS)/%.svg`

**Comment by ransford** [comment]
OK. It will take me a little time to reproduce this, since GNU Make 3.x doesn't seem to tickle this bug.

**Comment by peach-1s-me** [comment]
> 

Bro I also encountered this problem about :`$(OBJ_OUT_DIR)/%.o: $(CUR_DIR)/%.c`

**Comment by ransford** [comment]
There's almost certainly a space in a directory name in `$(FIGS)` (or in the case of the most recent comment, `$(OBJ_OUT_DIR)`). Try renaming component directories so that they don't have spaces in their names.
