### ISSUE TITLE
echo prints newline instead of \n

### ISSUE THREAD

**Issue by ArchdukeTim** [ransford/pdflatex-makefile#43]
Because the command to write to `revision.tex` uses the non-builtin version of echo, the \n is escaped to a newline character. My solution would be to use printf i.e `printf '\newcommand...{%s}' '$(REVISION)' > revision.tex`, though there might be a better way. 

I'm using zsh on macOS big sur

**Comment by ransford** [comment]
a98bbf9 should fix this. Thanks!
